language: node_js

sudo: false

cache:
  apt: true
  directories:
    - node_modules

node_js: stable

install:
  - npm install --force -D
  - cd ./test/smoke/template
  # - npm i --legacy-peer-deps
  - npm install --force -D
  - cd ../../../

script:
  - npm test
